### ISSUE TITLE
Need Go based bookinfo microservices to speedup testing

### ISSUE THREAD

**Issue by rshriram** [amalgam8/amalgam8#229]
The integration test is currently using the actual demo app that takes a lot of time of build (with Flask, bootstrap, etc.). Given that the integration test is running in non-interactive mode, we need Go based implementations of all the bookinfo microservices so that the app containers can be built and tested quickly. The go based test apps would also allow us to easily add additional test cases for testing A8 capabilities.

**Comment by zcahana** [comment]
I'm gonna take a crack at that.

Plan is to implement an identical set of services in Golang, and delete the Python ones.
Users who'd like to modify/rebuild the examples will need a Go-enabled environment. Others will just use the prebuilt Dockerhub images.

**Comment by rshriram** [comment]
You don't need identical set of services, in the sense that you don't need a bootstrap based UI, etc. The Go based version is intended only for testing. So, we could simply return JSONs/one line text from each microservice; the productpage service could simply collate the JSONs/text entries. Hopefully we would be able to use Gingo or something on the end to end system.
