### ISSUE TITLE
a8sidecar needs to provide a debug option to inspect routes in lua

### ISSUE THREAD

**Issue by rshriram** [amalgam8/amalgam8#255]
Need to provide commands like `a8sidecar inspect-routes` that should display the list of routes, rules etc., present in Lua. For this, a8sidecar should query lua and print it out for the user. This is much more user friendly than asking the user to query http://localhost:5813/a8-admin.

**Comment by GregHanson** [comment]
@rshriram are you suggesting a CLI for the sidecar, where the user will have to log into the sidecar container and run the commands?

**Comment by rshriram** [comment]
Yes. The curl we do, to inspect the lua state can be replaced by the cli. 
Instead of creating a new tool, we can just have a debug command like a8sidecar --debug show-lua-state or something along those lines. 

The cli can do more in future. Inspect lua state as well as compare it with sidecar's internal state.

**Comment by rshriram** [comment]
resolved by #335
