### ISSUE TITLE
Documentation updates for Bluemix deployment of Bookstore App

### ISSUE THREAD

**Issue by todkap** [amalgam8/amalgam8#291]
Walking through the instructions for deployment to Bluemix.   I may have missed some steps but thought it would be best to open an issue in case others hit this issue.   

**Two issues..**
1) Definition of the domain and route (did the set up in .bluemixrc) [see details below]
2) URL to bookstore app is not /productpage/productpage.  [I entered in http://todkap-a8-bookinfo.mybluemix.net/productpage?u=normal to get to it]

Looks like the command domain and hostname is missing that in deployInfo.sh
todkapmcbookpro:examples todd$ bluemix ic group-create
Incorrect Usage.
The command options or arguments were specified incorrectly. Review the following usage information and try entering the command again.

USAGE:
   bluemix ic group-create --name GROUP_NAME [--memory,-m MEMORY_SIZE] [-n,--hostname HOSTNAME] [-d,--domain DOMAIN] [--env,-e ENV_KEY=ENV_VAL] [--env-file ENVIRONMENT_VARIABLE_FILE] [--publish,-p PORT] [-P false|true] [--volume,-v VOLUME_NAME] [--min MIN_INSTANCE_COUNT] [--max MAX_INSTANCE_COUNT] [--desired DESIRED_INSTANCE_COUNT] [--anti false|true] [--bind SERVICE_INSTANCE_NAME] IMAGE_NAME [COMMAND [COMMAND ...]]

bluemix ic group-create --name bookinfo_productpage \
  --publish 9080 --memory 256 --auto --anti \
  --min 1 --max 2 --desired 1 \
  --env A8_REGISTRY_URL=$REGISTRY_URL \
  --env A8_REGISTRY_POLL=5s \
  --env A8_CONTROLLER_URL=$CONTROLLER_URL \
  --env A8_CONTROLLER_POLL=5s \
  --env A8_SERVICE=productpage:v1 \
  --env A8_ENDPOINT_PORT=9080 \
  --env A8_ENDPOINT_TYPE=http \
  --env A8_REGISTER=true \
  --env A8_PROXY=true \
  ${BLUEMIX_REGISTRY_HOST}/${BLUEMIX_REGISTRY_NAMESPACE}/${PRODUCTPAGE_IMAGE}

I entered the following in my container page..
bookinfo_productpage
Routes: todkap-a8-bookinfo.mybluemix.net

**Comment by rshriram** [comment]
Hi
 Can you please provide some information on the bluemix CLI version and CF cli version you are using? We have had multiple people try the exact same scripts. Seems you are hitting some version incompatibility issues w.r.t. bluemix cli.

**Comment by todkap** [comment]
Older CF version but bluemix appears up to date.

todkapmcbookpro:hellonode todd$ bluemix --version
bluemix version 0.4.2+d8c5ae7-2016-09-14T06:42:28+00:00

todkapmcbookpro:hellonode todd$ cf --version
cf version 6.16.1+924508c-2016-02-26

**Comment by rshriram** [comment]
Hi, I checked your app. Something is very odd. The productpage is always in /productpage/productpage. Could you redeploy the app please?

**Comment by rshriram** [comment]
closing as there has been no response.
