### ISSUE TITLE
issues (mostly doc) when playing with A8 today

### ISSUE THREAD

**Issue by linsun** [amalgam8/amalgam8#292]
1. Custom setup on examples didn't list if users can use his own kube or swarm cluster.  It is helpful to provide vagrant file to install kube or swarm but many users already have their kube env.  We need to provide docs on how user can configure A8 to work with an existing kubernetes (mini-kube for example).
2. deploy A8 control plane failed but everything seem to have worked.  Perhaps add a bit more retry?  seems a timing issue or explain in the doc that this is no issue by validating which cmds.

curl -w '%{http_code}' --max-time 10 http://localhost:31200/health -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (28) Operation timed out after 10001 milliseconds with 0 bytes received
- code=000
- '[' 000 = 200 ']'
- attempt=11
- '[' 11 -gt 10 ']'
- echo 'Timeout waiting for controller route: /health returned HTTP 000'
  Timeout waiting for controller route: /health returned HTTP 000
- echo 'Deploying the controlplane has failed'
  Deploying the controlplane has failed
- exit 1
  vagrant@vagrant-ubuntu-trusty-64:~/amalgam8/examples$ curl http://localhost:31200/health
1. "welcome to ngnix" needs to updated to welcome to open resty...
2. is it possible to have docker id added to the A8 service  API for a given service?  https://amalgam8.slack.com/archives/users/p1474472426000624
3. we should note specify default route when there is only 1 version of the service is optional in the doc, as they are not needed at all.

**Comment by rshriram** [comment]
Addressed (1), (2). 
Welcome to "nginx" stuff has been addressed as well.

As for adding the Docker ID to the A8 service version, it would require some scripting, breaking the demo experience. People can no longer do `docker-compose -f <>` or `kubectl create -f` . There would be scripts and stuff. Having scripts makes things hard for Windows users as well.
