### ISSUE TITLE
Sidecar fails when A8_SERVICE env variable is not set

### ISSUE THREAD

**Issue by zachidan** [amalgam8/amalgam8#308]
1. If the A8_SERVICE is not set, the nginx process fails to create the Amalgam8 lua object and then most of the calls to nginx fail with a nil pointer exception. A special validity check (including user-friendly error message) for the A8_SERVICE is required on startup.
2. The sidecar allows the user to provide command line arguments and/or env variables (e.g. --service or A8_SERVICE), but the nginx requires the user to provide ONLY env variables (nginx does NOT read the command line arguments of the sidecar). We need to either convert the command line arguments to env variables on the sidecar or to disable the command line arguments on the sidecar.

**Comment by rshriram** [comment]
@zachidan 
(2) is a real problem. Sidecar needs to set the A8_SERVICE environment variable before forking nginx.
