### ISSUE TITLE
Action rule without route rule is ignored

### ISSUE THREAD

**Issue by zachidan** [amalgam8/amalgam8#311]
When an action rule is defined (e.g., delay injection to request) with no route rule, the action is ignored.

I can think about scenario that the user want to do some action for each request (e.g., delay injection, request modification, response modification, etc.)

**Comment by rshriram** [comment]
Can you provide an example please? The rule you passed and the setup.

**Comment by zachidan** [comment]
@rshriram 

Here is the rule that I set -

{
   "revision": 0,
   "rules": [
      {
         "id": "1",
         "priority": 0,
         "destination": "TA_SERVICE_A8",
         "match": {
            "source": { "name" :"gateway"}
         },
         "actions": [
            {
               "action": "abort",
               "probability": 1,
               "return_code": 513
            }
         ]
      }
   ]
}

Based on the code (Line 720 at amalgam8.lua module), you can see the condition that requires selected_backend to be not nil:

if selected_backend and actions then
