### ISSUE TITLE
Kubernetes Adapter Catalog should not prefix endpoint value 

### ISSUE THREAD

**Issue by frankbu** [amalgam8/amalgam8#313]
The parseEndpoint function in catalog.go, the adapter is setting the endpoint value like this (line 223):

```
        endpointValue = fmt.Sprintf("%s://%s", endpointType, endpointValue)
```

It should not be adding the http/https prefix to the value, but rather leave it as a simple IP:PORT value,
so this line needs to be removed.

**Comment by zcahana** [comment]
This issue demonstrates why pushing directly to master is bad: in this case - the code change is not aligned with existing unit-tests, which now fail. The result is a [broken master branch](https://travis-ci.org/amalgam8/amalgam8/builds/163837779), as well as [broken PRs](https://travis-ci.org/amalgam8/amalgam8/builds/164401892) which have this commit in their commit history.

A PR with the above commit would have caught this immediately in the Travis build.
