### ISSUE TITLE
Eureka adapter: allow eureka users to set Amalgam8 tags for version-based routing

### ISSUE THREAD

**Issue by zachidan** [amalgam8/amalgam8#317]
The sidecar supports version-based routing by using instance tags.

To allow eureka users to use version-based routing, it is required to allow them to set the tags array. My suggestion is to map the **eureka.metadata.tags** instance property to the Amalgam8 **tags array** instance property.

**Comment by rshriram** [comment]
Let's not close this issue until we have a documentation in place. No point in having undocumented features. Please add the documentation (markdown format) to amalgam8.github.io repository.

**Comment by rshriram** [comment]
@zcahana @zachidan

**Comment by zcahana** [comment]
Good point. This was a premature use of the "closes #317" syntax.

**Comment by zachidan** [comment]
Documentation has been added - https://github.com/amalgam8/amalgam8.github.io/pull/76

**Comment by rshriram** [comment]
Where is the documentation for the eureka catalog?
