### ISSUE TITLE
Filesystem catalog -- read files with .json extension instead of .conf

### ISSUE THREAD

**Issue by rshriram** [amalgam8/amalgam8#330]
File system catalog reads static instance information from a file, where the content should be in JSON format. However, it requires the file to be named as a `.conf`, which is a slightly unorthodox naming convention for a JSON document.

**Comment by zcahana** [comment]
@rshriram 2 PRs submitted for code/docs updates. Please merge together.

**Comment by rshriram** [comment]
fixed by #331
