### ISSUE TITLE
Need ability to call gremlin as a service from the new GO based CLI

### ISSUE THREAD

**Issue by jemcginn** [amalgam8/amalgam8#381]
Another item associated with supporting the new Go CLI is the requirement to call Gremlin as a service. There's a python server here: https://github.com/amalgam8/gremlin/blob/master/app.py	
GitHub
amalgam8/gremlin

Somebody needs to create a docker image, built it, and make the changes to the controlplane startup yaml files to run it.  

In order for the 'a8ctl recipe-run' command to runn successfully, it will need to have the Gremlin server up and running in the controlplane before it can be tested.

**Comment by jemcginn** [comment]
1) Dockerize the service for gremlin (provide an API, handle requests, return responses)  - blocking
2) Cleanup of the code - Shriram will provide some additional notes on what is needed for this.

**Comment by JacobFrericks** [comment]
@rshriram do you have any comments on step 2 provided in the previous comment?

**Comment by rshriram** [comment]
resolved by #433 and #429
