### ISSUE TITLE
Desired vs actual state verification between controller and sidecar/proxy

### ISSUE THREAD

**Issue by rshriram** [amalgam8/amalgam8#389]
Just like the desired state vs actual state concept, we need a way for the operator to check if the rules that she submitted to the control plane (A8 controller) have made it to the sidecars and whether those rules have been accepted or not.

Today, the controller responds with a 200 OK when a rule is submitted, and users assume that the rule has been activated in all sidecars, which is never the case. We need to make this explicit.
A common problem that arises in this case is when the user submits a set of rules and expects them to kick in instantaneously (e.g., fault injection). If the gateway/sidecars had lost connectivity to the controller, it may take a while before they re-establish connectivity and obtain the new rules.

The controller should provide an API to check the state of rules in the system. Asynchronously, it should check in with the sidecars (or sidecars check in with controllers) that they have received a the latest batch of rules, processed and updated the proxies.

The first focus for this implementation should be on kubernetes.

**Comment by GregHanson** [comment]
I'm not sure it would be the controller's responsibility to query the sidecars/gateway to verify that each is running with the correct rules.  Don't think the controller should have to know which containers in a K8S cluster are running nginx/envoy, let alone an IP or url to contact each of them.  I would advocate possibly modifying the sidecar poll logic to the controller to send it some sort of ID that the controller could cache and return along with the rule version controller gave to that sidecar in the last poll.
