### ISSUE TITLE
Sidecar should obtain TLS certs and other configs from ConfigMaps in K8S

### ISSUE THREAD

**Issue by rshriram** [amalgam8/amalgam8#392]
Instead of setting up the sidecar with configurations via environment variables/config files, in kubernetes, the sidecar should read all the relevant configurations from a predefined ConfigMap object and setup the proxy accordingly.

**Comment by zcahana** [comment]
My understanding of ConfigMaps is that consumers (i.e., containers) do not directly reference ConfigMaps via an API, but rather via environment variables and/or mounted volumes. K8s provides means to populate the environment and/or volumes from existing ConfigMaps.

Given that the sidecar already supports getting its config from environment/files, what else is missing?

**Comment by rshriram** [comment]
You are right. I think the sidecar has to be able to pull secrets (for TLS), related to the work @paulben is doing. Specifically, we might need a provision in the config where the user can specify how to obtain the certs (vault, k8s secret, files).
i think the rest can be resolved with docs.
