### ISSUE TITLE
Provide updated documentation for the examples and a8ctl usage based on the new Go based CLI

### ISSUE THREAD

**Issue by jemcginn** [amalgam8/amalgam8#393]
The a8ctl is undergoing changes to allow flexibility in how it defines rules and runs the gremlin recipes.  At the time this new CLI gets integrated into the A8 repository, we will need to have updated documentation both for the CLI usage and we will also need the documentation for the existing examples (helloworld and bookinfo) modified to use the new / modified CLI commands.

**Comment by dougbeauchene** [comment]
I'm starting to take a look at the changes to the Helloworld and Bookinfo doc changes that would be needed for this.

**Comment by dougbeauchene** [comment]
I'm going to pause any further work on CLI doc related updates until the CLI design gets a little further toward closure.
