### ISSUE TITLE
Reworking the logserver

### ISSUE THREAD

**Issue by JacobFrericks** [amalgam8/amalgam8#395]
The logserver doesn't seem to work with Kubernetes and minikube. It cycles between states `Running`, `Terminated: Error`, `Waiting: CrashLoopBackOff`

A possible solution would be to tweak filebeat to log directly to elasticsearch and build sidecar, productpage and reviews containers.

**Comment by rshriram** [comment]
Closing this as we have narrowed down the issue to Elasticsearch's mmapfs & increasing mmap_count problem (https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html). This has been documented as well in the Amalgam8 docs. Users have to increase the mmap count when running A8 on linux VMs (minikube, vagrant).
