### ISSUE TITLE
CI/CD - Automate the uploading of the example images to dockerhub

### ISSUE THREAD

**Issue by jemcginn** [amalgam8/amalgam8#404]
This issue is for discussing and implementing the steps required to automate the publishing of the helloworld and bookinfo images to dockerhub.

This is one aspect of the automation needed to satisfy the overall goals laid out in issue https://github.com/amalgam8/amalgam8/issues/406

**Comment by ijsnellf** [comment]
Right now I perform the following manual steps for each A8 release (most relevant portion in **bold**):

 1. Update changelog.
 1. Update Dockerhub images to install new release.
 1. Create interim release.
 1. Build bookinfo/helloworld app images.
 1. Verify bookinfo/helloworld demo steps in K8S and Docker environments.
 1. Make release public.
 1. **Push bookinfo/helloworld images to Dockerhub.**

Right now I run this bash command to upload the images

```bash
for i in "amalgam8/a8-examples-helloworld-sidecar:v1" "amalgam8/a8-examples-helloworld-sidecar:v2" "amalgam8/a8-examples-helloworld:v1" "amalgam8/a8-examples-helloworld:v2" "amalgam8/a8-examples-bookinfo-ratings-sidecar:v1" "amalgam8/a8-examples-bookinfo-ratings:v1" "amalgam8/a8-examples-bookinfo-reviews:v3" "amalgam8/a8-examples-bookinfo-reviews-sidecar:v2" "amalgam8/a8-examples-bookinfo-reviews-sidecar:v3" "amalgam8/a8-examples-bookinfo-reviews:v2" "amalgam8/a8-examples-bookinfo-reviews-sidecar:v1" "amalgam8/a8-examples-bookinfo-reviews:v1" "amalgam8/a8-examples-bookinfo-details-sidecar:v1" "amalgam8/a8-examples-bookinfo-details:v1" "amalgam8/a8-examples-bookinfo-productpage-sidecar:v1" "amalgam8/a8-examples-bookinfo-productpage:v1" "amalgam8/a8-controller:latest" "amalgam8/a8-registry:latest" "amalgam8/a8-sidecar:alpine"; do docker push $i; done
```

**Comment by craigyam** [comment]
Merged
