### ISSUE TITLE
CI/CD Automate the testing of the examples (bookinfo / helloworld) prior to releasing a new version of A8

### ISSUE THREAD

**Issue by jemcginn** [amalgam8/amalgam8#405]
This item is for creating automated testing of the bookinfo and helloworld examples in the various deployment environments, prior to releasing a new version of A8.  Currently test automation via travis already exists for the controller, registry, and sidecar prior to delivering a new release.  This item is for extending that test automation to the examples (to ensure the examples will work with any new changes to the controller, registry, and sidecar).

Refer to the description in #406 to see how this item plays into the overall A8 release automation goals.

**Comment by ijsnellf** [comment]
Right now I perform the following manual steps for each A8 release (most relevant portion in **bold**):

 1. Update changelog.
 1. Update Dockerhub images to install new release.
 1. Create interim release.
 1. Build bookinfo/helloworld app images.
 1. **Verify bookinfo/helloworld demo steps in K8S and Docker environments.**
 1. Make release public.
 1. Push to bookinfo/helloworld Dockerhub.

**Comment by craigyam** [comment]
Addressed by PRs #468 and #472
