### ISSUE TITLE
Go CLI: rule-get should return yaml by default

### ISSUE THREAD

**Issue by frankbu** [amalgam8/amalgam8#410]
`a8ctl-beta rule-get` is returning JSON by default instead of YAML. The default when `-o` is not specified should be YAML. For JSON output the `-o json` must be set.

**Comment by gicaceres** [comment]
Implemented https://github.com/amalgam8/amalgam8/pull/433/commits/e70ffe805fc69598371dff7c1742d4780689cc0c
