### ISSUE TITLE
Go CLI: rule-create must support input from a single batch file

### ISSUE THREAD

**Issue by frankbu** [amalgam8/amalgam8#411]
The CLI needs to support the `-` value for the `-f` option (i.e., `-f -`) so that commands can be invoked in a standalone script file, like the following example:
```
$ cat <<EOF | a8ctl-beta rule-create -f -
- destination: reviews
  priority: 1
  route:
    backends:
    - tags:
      - v1
EOF
```

**Comment by gicaceres** [comment]
Implemented https://github.com/amalgam8/amalgam8/pull/433/commits/d59596aa0ed6f9529d89f294679040346b18ba49

Use `-r` instead of `-f -` 
```
$ cat << EOF | a8ctl-beta rule-create -r
rules:
- destination: reviews
  priority: 1
  route:
    backends:
      - tags:
         - v1
EOF
```
