### ISSUE TITLE
Go CLI: the top level "rule" property in the rules API payload should not appear in the CLI

### ISSUE THREAD

**Issue by frankbu** [amalgam8/amalgam8#413]
The request and response bodies from HTTP POST and GET of the Rules API includes a top-level "rules" property like this:
```
{ "rules": [ ... ] }
```
The CLI should not require the user to include this extra top level wrapper in `rule-create` and should not include it in the output from `rule-get`. They should simply accept and return the list of rules in JSON:
```
[
  { rule1 }.
  { rule2 }.
  ...
  { ruleN }
]
```
or in YAML:
```
- rule1
- rule2
...
- ruleN
```

**Comment by rshriram** [comment]
@gicaceres if this is addressed in the current CLI, please close this issue.
