### ISSUE TITLE
Go CLI: add missing `traffic-*` commands

### ISSUE THREAD

**Issue by frankbu** [amalgam8/amalgam8#415]
The `traffic-start`, `traffic-step`, and `traffic-abort` commands are needed before the new Go CLI can replace the old python a8ctl.

**Comment by gicaceres** [comment]
`traffic-start` https://github.com/amalgam8/amalgam8/pull/433/commits/1f8349c5ddbbd09318cdc3f3ad29def670008dde
`traffic-step` https://github.com/amalgam8/amalgam8/pull/433/commits/1549c49e4a92859093c6a6fb00570bc05d6622d0
`traffic-abort` https://github.com/amalgam8/amalgam8/pull/433/commits/9e6051f34c1e5b4aa351ad0d38968cdca1f686bd
