### ISSUE TITLE
Automatic inference of service name and tags in Kubernetes

### ISSUE THREAD

**Issue by zcahana** [amalgam8/amalgam8#426]
When running in Kubernetes, the sidecar can automatically "discover" the name of the service(s) the local pod implements, as well as the tags (labels) attached to it.
This will relieve users from maintaining the service name and labels both in their kubernetes pod YAMLs and the amalgam8 configuration YAML.

**Comment by zcahana** [comment]
Two issues to consider:
1. A pod may implement more than one service. How do we support this in the proxy, so that source-based rules can apply?
2. Services and labels are dynamic. Service definitions as well as pod labels may change during its runtime, which may cause it to start/stop implementing a particular service at any time.

Slack input from @elevran @rshriram on the above:
> elevran [3:35 PM]  
> I don't think this will be common - we can safely ignore multi-service pods and just grab one (possibly warn on more than one)

> shriram [5:23 PM]  
> So, don’t assume that a pod will not be part of multiple services.
> The k8s guys kept insisting that we should not make such an assumption.
> there is an ongoing discussion for that.
> As far as the proxy is concerned, the change is small enough, but the semantics get ugly. (pods which are part of multiple services: how will the logs look?)
> I suggest we make an explicit note that if you have pods as part of multiple services, its your mess. 
> We support pods as part of one headless service only.

**Comment by zcahana** [comment]
@rshriram so, based on your latest remark (_We support pods as part of one headless service only_), you too suggest that in case of a multi-service pod, pick one service and ignore the others?

Also, note that we do not restrict to headless services alone. We support headed (kube-proxied) services too.

**Comment by rshriram** [comment]
@zcahana So, the whole name business is where things are getting painful. What we can do is, we can automatically pick up the pod name. And thats it. We need to rework our examples to focus on just the source labels and avoid naming the sources. what do you think?

**Comment by zcahana** [comment]
In terms of expressiveness, writing source-based rules using only labels (without service name) is equally expressive, because a service name is a function of a pod labels. In terms of ease of use, using service names is clearly easier and reduce duplication. Either way, our rules DSL is using service names, and rewriting our examples won't change it (only hide it), so we can't ignore it alltogether.

 I would say that for first pass, let's go with @elevran suggestion to pick up only one service name, and warn when there are multiple. I believe that for a proper support of this, we'll anyway need to change the proxy(ies) to be able to accept multiple service names and labels, multiple times (to support dynamic updates to services & labels), and at any time (to support failed/retried attempts to contact kube API).

**Comment by rshriram** [comment]
Rules DSL has support for source tags. And the source name is optional. But I am okay with the assumption that pods can be part of a single service only (as first iteration). What does this entail? The registry should properly escape tags/labels and other sanitization stuff ?

PR #424 depends on this right? And when this feature gets implemented, we need to make sure to change the docker examples such that the service names are provided as "reviews:version=v1". This format will ensure that people have to use just a single gremlin config file whether its docker or kubernetes (keeps docs cleaner as well).

**Comment by zcahana** [comment]
PR #424 doesn't depend on this, it can be merged as is (once we validate registry support for "key=value" tags).

After we implement this feature, we can optionally change the examples to utilize it, given that it won't complicate the examples (e.g., separate files for docker vs. kubernetes).
