### ISSUE TITLE
Rename --discovery_backend and --rules_backend flags

### ISSUE THREAD

**Issue by GregHanson** [amalgam8/amalgam8#446]
``` const (
 	configFlag              = "config"
 	registerFlag            = "register"
 	proxyFlag               = "proxy"
	proxyAdapterFlag        = "proxy_adapter"
```

@zcahana recommended the following: 
> I'm wondering if we need to rename --discovery_backend and --rules_backend to --discovery_adapter and --rules_adapter. Consistency is never a bad thing, and --proxy_backend doesn't sound right. 

This is a breaking change so opening this issue for tracking what will be a new Pull Request

**Comment by zcahana** [comment]
Renaming --discovery_backend and --rules_backend is not a breaking change because these flags were never released. Both are post-[v0.4.2](https://github.com/amalgam8/amalgam8/blob/v0.4.2/sidecar/config/flags.go).
