### ISSUE TITLE
Documentation for local Docker installation outdated

### ISSUE THREAD

**Issue by torstenandrecht** [amalgam8/amalgam8#469]
https://www.amalgam8.io/docs/demo-helloworld.html
...
Note: If you are using Docker Toolbox on the Mac, use $(docker-machine ip default):32000 instead of localhost:32000
....

Docker Toolbox is outdated. What is the right expoirt for docker for mac

**Comment by zcahana** [comment]
Hi @torstenandrecht,

[Docker Toolbox](https://www.docker.com/products/docker-toolbox) is definitely not outdated. However, referring to *Docker Machine* may be more accurate here. Also, confining this to _Mac_ users is incorrect - this can be relevant to Windows/Linux users too.

**Comment by zcahana** [comment]
Resolved via amalgam8/amalgam8.github.io@9d3d9043c320e3bcfe40b1687266c81a2601df3d.
