### ISSUE TITLE
Documentation for amalgam8 setup on bluemix outdated

### ISSUE THREAD

**Issue by torstenandrecht** [amalgam8/amalgam8#470]
Source: https://www.amalgam8.io/docs/demo-setup.html

examples fro wrong commands:

wrong => bluemix ic init
right => cf ic init

wrong => bluemix ic namespace-get
right => cf ic namespace get

Please update the whole setup page and following documents for a successful installation.

**Comment by zcahana** [comment]
Hi @torstenandrecht,

The `bluemix` CLI is _not_ outdated, and is in fact the primary CLI used for Bluemix nowadays.
Please re-open if you think that there are other issues with the Bluemix-setup instructions.
