### ISSUE TITLE
Integrate the K8s rules controller in testing frameworks

### ISSUE THREAD

**Issue by elevran** [amalgam8/amalgam8#474]
The K8s rules controller needs to be properly integrated in testing frameworks and run tests for every PR

**Comment by ijsnellf** [comment]
@elevran: is this with respect to using Third Party Resources to store rules in our tests?

**Comment by jemcginn** [comment]
P1 - Needed for running bookinfo in K8S

**Comment by craigyam** [comment]
Created PR https://github.com/amalgam8/amalgam8/pull/510 for helloworld automation.

**Comment by craigyam** [comment]
PR https://github.com/amalgam8/amalgam8/pull/513 for bookinfo automation has been merged.
