### ISSUE TITLE
Need Envoy based ingress controller for kubernetes

### ISSUE THREAD

**Issue by rshriram** [amalgam8/amalgam8#483]
Ingress controller will allow us to get rid of the gateway.

**Comment by jemcginn** [comment]
P2 - NGINX parity

**Comment by jemcginn** [comment]
Had discussion with Etai.  This item was implemented in Istio.  Etai indicated this was not a nginx parity item for A8.  This would be additional capability in A8 not currently provided via the Nginx based A8 implementation.  Recategorizing this item as P3, and removing it from this issue from the milestone.

**Comment by elevran** [comment]
starting with https://github.com/istio/manager/pull/71, Istio now has an ingress controller based on Envoy. Any further ingress work will be done on the [Istio side](https://github.com/istio/manager/tree/master/proxy/envoy), and shared between the projects
