### ISSUE TITLE
Leverage Envoy CDS

### ISSUE THREAD

**Issue by ijsnellf** [amalgam8/amalgam8#486]
Envoy supports using a Cluster Discovery Service to dynamically redefine clusters. The Sidecar should take advantage of this capability when the Envoy adapter is in use.

**Comment by jemcginn** [comment]
P2 - Nginx parity - Needed for speeding up reloads

**Comment by GregHanson** [comment]
blocked by incoming change to envoy code, should be in by end of week

**Comment by GregHanson** [comment]
Solved by PR #501
