### ISSUE TITLE
Explore using Envoy for inbound & outbound traffic

### ISSUE THREAD

**Issue by rshriram** [amalgam8/amalgam8#491]
Currently, we have a clunky model, where the app handles incoming connections and uses Envoy for outgoing connections. We need to use Envoy for both incoming and outgoing connections, so that it can terminate TLS connections, and talk to other Envoys via HTTP/2, do health checks, etc.

In Bluemix/CloudFoundry cases, it would require creating two listeners. External listener for receiving connections from outside the container/app. Internal listener for receiving connections from app to Envoy. Access logging needs to be enabled only for internal listener.

In kubernetes case, we can use single listener and use the ip tables forwarding setup #482 , to automatically handle all connections.

In both cases, we need to pick a random port in the upper half (32000+) for Envoy, so that it does not collide with application's port. Note that these ports need to be configurable, so that in cloud foundry case, Envoy can be made to listen on VCAP_ENV_PORT.

**Comment by jemcginn** [comment]
P4 - Not needed for Bookinfo or Nginx parity
