### ISSUE TITLE
Include new a8ctl binaries in release and remove -beta from name.

### ISSUE THREAD

**Issue by craigyam** [amalgam8/amalgam8#526]
The a8ctl binaries should be uploaded to github as part of a release.
- Add make release.cli target
- Remove "-beta" from the name
- Update the test scripts to use the updated name

**Comment by rshriram** [comment]
Can this be closed ?

**Comment by craigyam** [comment]
Addressed by https://github.com/amalgam8/amalgam8/pull/527
